# Defino el objetivo (goal)
geometry_msgs/Pose2D target_pose
---
# Defino el resultado (result)
geometry_msgs/Pose2D target_pose
---
# Defino la realimentacion (feedback)
float32 distance_to_goal
geometry_msgs/Pose2D current_pose
